name: smart_greenhouse
description: Smart Greenhouse Dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.8
  flutter_launcher_icons: ^0.14.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_native_splash:
  color: "#E9F7EF"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#E9F7EF"
    image: assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"