services:
  postgres:
    image: postgres:16
    container_name: smart_greenhouse_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_greenhouse
    ports:
      - "5432:5432"
    volumes:
      - smart_greenhouse_data:/var/lib/postgresql/data

volumes:
  smart_greenhouse_data: